import { boolean, index, integer, jsonb, pgEnum, pgTable, primaryKey, real, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";

export const trackEnum = pgEnum("track", ["CODING","SQL","SYSTEM_DESIGN","ML_SYSTEM_DESIGN","OOD","BEHAVIORAL"]);
export const difficultyEnum = pgEnum("difficulty", ["EASY","MEDIUM","HARD"]);
export const moderationEnum = pgEnum("moderation_status", ["RECEIVED","EXTRACTED","DEDUPED","REVIEW_REQUIRED","APPROVED","PUBLISHED","REJECTED"]);

export const users = pgTable("users", { id: uuid("id").defaultRandom().primaryKey(), email: text("email").notNull(), displayName: text("display_name"), createdAt: timestamp("created_at", {withTimezone:true}).defaultNow().notNull() }, t => [uniqueIndex("users_email_uq").on(t.email)]);
export const companies = pgTable("companies", { id: uuid("id").defaultRandom().primaryKey(), slug:text("slug").notNull(), name:text("name").notNull(), website:text("website"), createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull() }, t=>[uniqueIndex("companies_slug_uq").on(t.slug)]);
export const questions = pgTable("questions", { id:uuid("id").defaultRandom().primaryKey(), slug:text("slug").notNull(), title:text("title").notNull(), track:trackEnum("track").notNull(), difficulty:difficultyEnum("difficulty").notNull(), summary:text("summary").notNull(), constraints:jsonb("constraints").$type<string[]>().default([]).notNull(), skills:jsonb("skills").$type<string[]>().default([]).notNull(), hints:jsonb("hints").$type<string[]>().default([]).notNull(), reportCount:integer("report_count").default(0).notNull(), confidence:real("confidence").default(0).notNull(), frequencyScore:real("frequency_score").default(0).notNull(), lastReportedAt:timestamp("last_reported_at",{withTimezone:true}), published:boolean("published").default(false).notNull(), createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull(), updatedAt:timestamp("updated_at",{withTimezone:true}).defaultNow().notNull() }, t=>[uniqueIndex("questions_slug_uq").on(t.slug), index("questions_track_idx").on(t.track), index("questions_last_reported_idx").on(t.lastReportedAt)]);
export const questionCompanies = pgTable("question_companies", { questionId:uuid("question_id").notNull().references(()=>questions.id,{onDelete:"cascade"}), companyId:uuid("company_id").notNull().references(()=>companies.id,{onDelete:"cascade"}), reportCount:integer("report_count").default(0).notNull(), confidence:real("confidence").default(0).notNull(), lastReportedAt:timestamp("last_reported_at",{withTimezone:true}) }, t=>[primaryKey({columns:[t.questionId,t.companyId]})]);
export const sourceDocuments = pgTable("source_documents", { id:uuid("id").defaultRandom().primaryKey(), sourceType:text("source_type").notNull(), sourceUrl:text("source_url").notNull(), fingerprint:text("fingerprint").notNull(), rawText:text("raw_text"), copyrightStatus:text("copyright_status").default("UNKNOWN").notNull(), moderationStatus:moderationEnum("moderation_status").default("RECEIVED").notNull(), retrievedAt:timestamp("retrieved_at",{withTimezone:true}).defaultNow().notNull() }, t=>[uniqueIndex("source_documents_fingerprint_uq").on(t.fingerprint)]);
export const interviewReports = pgTable("interview_reports", { id:uuid("id").defaultRandom().primaryKey(), sourceDocumentId:uuid("source_document_id").references(()=>sourceDocuments.id,{onDelete:"set null"}), companyId:uuid("company_id").references(()=>companies.id,{onDelete:"set null"}), role:text("role"), interviewStage:text("interview_stage"), reportedAt:timestamp("reported_at",{withTimezone:true}), extractionConfidence:real("extraction_confidence").default(0).notNull(), moderationStatus:moderationEnum("moderation_status").default("REVIEW_REQUIRED").notNull(), createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull() });
export const questionReports = pgTable("question_reports", { id:uuid("id").defaultRandom().primaryKey(), questionId:uuid("question_id").notNull().references(()=>questions.id,{onDelete:"cascade"}), interviewReportId:uuid("interview_report_id").notNull().references(()=>interviewReports.id,{onDelete:"cascade"}), confidence:real("confidence").notNull(), evidenceNotes:text("evidence_notes"), createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull() }, t=>[uniqueIndex("question_report_pair_uq").on(t.questionId,t.interviewReportId)]);
export const attempts = pgTable("attempts", { id:uuid("id").defaultRandom().primaryKey(), userId:uuid("user_id").notNull().references(()=>users.id,{onDelete:"cascade"}), questionId:uuid("question_id").notNull().references(()=>questions.id,{onDelete:"cascade"}), status:text("status").notNull(), language:text("language"), score:real("score"), startedAt:timestamp("started_at",{withTimezone:true}).defaultNow().notNull(), completedAt:timestamp("completed_at",{withTimezone:true}) }, t=>[index("attempts_user_idx").on(t.userId),index("attempts_question_idx").on(t.questionId)]);
export const forumPosts = pgTable("forum_posts", { id:uuid("id").defaultRandom().primaryKey(), userId:uuid("user_id").notNull().references(()=>users.id,{onDelete:"cascade"}), companyId:uuid("company_id").references(()=>companies.id,{onDelete:"set null"}), category:text("category").notNull(), title:text("title").notNull(), body:text("body").notNull(), moderationStatus:moderationEnum("moderation_status").default("REVIEW_REQUIRED").notNull(), reactionCount:integer("reaction_count").default(0).notNull(), replyCount:integer("reply_count").default(0).notNull(), viewCount:integer("view_count").default(0).notNull(), createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull() }, t=>[index("forum_created_idx").on(t.createdAt)]);
export const forumReplies = pgTable("forum_replies", { id:uuid("id").defaultRandom().primaryKey(), postId:uuid("post_id").notNull().references(()=>forumPosts.id,{onDelete:"cascade"}), userId:uuid("user_id").notNull().references(()=>users.id,{onDelete:"cascade"}), body:text("body").notNull(), createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull() });
export const aiUsage = pgTable("ai_usage", { id:uuid("id").defaultRandom().primaryKey(), userId:uuid("user_id").references(()=>users.id,{onDelete:"set null"}), questionId:uuid("question_id").references(()=>questions.id,{onDelete:"set null"}), provider:text("provider").notNull(), model:text("model").notNull(), inputTokens:integer("input_tokens").default(0).notNull(), outputTokens:integer("output_tokens").default(0).notNull(), costMicros:integer("cost_micros").default(0).notNull(), createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull() }, t=>[index("ai_usage_created_idx").on(t.createdAt)]);
export const subscriptions = pgTable("subscriptions", { id:uuid("id").defaultRandom().primaryKey(), userId:uuid("user_id").notNull().references(()=>users.id,{onDelete:"cascade"}), providerCustomerId:text("provider_customer_id"), providerSubscriptionId:text("provider_subscription_id"), plan:text("plan").notNull(), status:text("status").notNull(), currentPeriodEnd:timestamp("current_period_end",{withTimezone:true}), createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull() }, t=>[uniqueIndex("subscriptions_provider_uq").on(t.providerSubscriptionId)]);
export const referralCodes = pgTable("referral_codes", { id:uuid("id").defaultRandom().primaryKey(), userId:uuid("user_id").notNull().references(()=>users.id,{onDelete:"cascade"}), code:text("code").notNull(), enabled:boolean("enabled").default(true).notNull(), createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull() }, t=>[uniqueIndex("referral_code_uq").on(t.code)]);
export const referralEvents = pgTable("referral_events", { id:uuid("id").defaultRandom().primaryKey(), referralCodeId:uuid("referral_code_id").notNull().references(()=>referralCodes.id,{onDelete:"cascade"}), referredUserId:uuid("referred_user_id").notNull().references(()=>users.id,{onDelete:"cascade"}), status:text("status").notNull(), creditCents:integer("credit_cents").default(0).notNull(), createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull() });
